#!/usr/bin/env python3
"""Add a Korean reading guide to an existing run; no load test is executed."""
import json
from pathlib import Path
p=Path(__file__).resolve().parents[1]/'build/load'
r=json.loads((p/'result.json').read_text()); m=r['metrics']
d=m['http_req_duration']; c=m['reservations_created']['count']; sold=m['reservations_sold_out']['count']
assert r.get('nginx') is True, 'This guide describes the Nginx comparison run only'
html='''<!doctype html><html lang="ko"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>1,000 VU 실험 · 한글 해설</title><style>
*{box-sizing:border-box}body{margin:0;background:#f4f6f8;color:#182637;font:16px/1.8 system-ui,-apple-system,sans-serif}main{max-width:1080px;margin:auto;padding:44px 24px}h1{font-size:36px;line-height:1.3}h2{font-size:24px;margin-top:0}h3{margin-bottom:6px}p{margin:10px 0}a{color:#125bc3}section,.card{background:white;border:1px solid #dce3ea;border-radius:14px;padding:25px;margin:20px 0}.cards{display:grid;grid-template-columns:repeat(3,1fr);gap:14px}.card{margin:0}.value{font-size:29px;font-weight:750;color:#115e59}.tag{font-size:13px;color:#52706c;letter-spacing:.05em}.note{background:#eef5ff;border-left:4px solid #3172bd;padding:15px}.warn{background:#fff6df;border-left:4px solid #c89420;padding:15px}table{width:100%;border-collapse:collapse}th,td{text-align:left;padding:12px;border-bottom:1px solid #e3e8ed;vertical-align:top}small{color:#526273}details{border-top:1px solid #e3e8ed;padding:15px 0}summary{cursor:pointer;font-weight:650}iframe{width:100%;height:850px;border:1px solid #ccd6e0;background:white}code{background:#eef1f5;padding:2px 5px;border-radius:4px}nav{display:flex;flex-wrap:wrap;gap:18px}.table{overflow:auto}@media(max-width:650px){.cards{grid-template-columns:1fr}h1{font-size:28px}main{padding:22px 14px}section{padding:18px}iframe{height:620px}}
</style><main><div class="tag">COMMERCE LAB · 2026-09-11 11:27 KST · NGINX 경유 실험</div>
<h1>연결 오류는 없었다.<br>그렇다면 성능도 충분한 걸까?</h1>
<p>이번 결과는 <b>이 부하에서 연결 오류와 예약 정합성 검사를 통과했다</b>는 뜻입니다. 초당 예약 3천 건을 성공시켰거나 운영 성능을 보장한다는 뜻은 아닙니다.</p>
<nav><a href="#read">① 결과 읽기</a><a href="#meaning">② 지표 사전</a><a href="#charts">③ 원본 그래프</a><a href="result.json">측정 원본 JSON</a><a href="k6-report.html" target="_blank">k6 리포트 별도 열기</a></nav>
<div class="cards"><div class="card"><small>HTTP 실패율</small><div class="value">FAILURE</div><small>매진 409는 정상 응답으로 분류</small></div><div class="card"><small>전체 HTTP p95</small><div class="value">P95 ms</div><small>요청 약 95%가 이 시간 이내</small></div><div class="card"><small>예약 생성 / 매진</small><div class="value">CREATED / SOLD</div><small>전체 예약 시도 중 생성 비율 SHARE%</small></div></div>
<section id="read"><h2>① 이 순서로 읽어보세요</h2>
<h3>1. 우리가 어떤 부하를 줬는가?</h3><p><code>k6 → Nginx → JDK HTTP 서버 → Spring 서비스 → MySQL 8.4.9</code></p><p>60초 동안 50 → 200 → 500 → 1,000 VU로 올리고 마지막에 0으로 낮췄습니다. 최대 부하 1,000 VU 유지 구간은 10초입니다. 각 가상 사용자는 정원 1인 같은 이벤트를 예약하고, 성공하면 취소합니다.</p><p class="note"><b>VU는 가상 사용자 수</b>입니다. TCP 연결 수나 동시에 실행되는 DB 트랜잭션 수와 같지 않습니다. HTTP worker는 128개, DB 풀은 최대 32개이며 같은 이벤트의 행 잠금에서 경합합니다.</p>
<h3>2. 요청과 데이터가 올바른가?</h3><p>HTTP 실패율 FAILURE, 응답·종료 검사 CHECKS회 통과. 최종 <b>잔여 FINALREMAIN · 예약 FINALRES</b>, 서버 업무 예외 ERRORS건입니다. 관찰한 DB 표본에서 잔여+예약=1 불변식 위반은 VIOLATIONS건입니다.</p><p>생성 CREATED건, 취소 CANCELLED건인 이유는 테스트 시작 때 기존 예약 1건을 먼저 취소했기 때문입니다. <code>초기 예약 1 + 생성 − 취소 = 최종 예약 0</code>으로 맞습니다.</p><p class="warn">검사 통과는 작성된 검사 범위의 통과입니다. DB 표본은 약 2초 간격이므로 모든 순간을 증명하지 않습니다. 기존 MySQL 통합 테스트의 ‘없는 이벤트 예약’ 실패는 별개로 남아 있습니다.</p>
<h3>3. 처리량을 예약 성공량과 구분하기</h3><p>총 REQUESTS HTTP 요청, 평균 <b>RPS req/s</b>입니다. 여기에는 매진 응답과 취소·상태 조회도 포함됩니다. 예약 생성은 CREATED건, 약 CREATE_RATE건/초입니다.</p><p class="warn">매진 응답이 예약 시도의 대부분(SOLD_SHARE%)입니다. 따라서 전체 p95는 주로 매진 응답의 영향을 받습니다. 성공 예약 API의 p95는 현재 요약 JSON만으로 따로 계산할 수 없습니다.</p>
<h3>4. 느린 구간은 어디인가?</h3><p>전체 평균 AVG ms, 중앙값 MED ms, p95 P95 ms, 최대 MAX ms입니다. 응답 첫 바이트를 기다린 시간의 평균은 155.740ms로, 전체 요청 시간 평균과 거의 같습니다. 데이터를 전송하는 시간보다 응답을 기다리는 시간이 지배적입니다.</p><p>이 대기에는 Nginx·HTTP worker·DB 풀·행 잠금·업무 실행이 섞여 있습니다. <b>이 지표만으로 DB 락이 모든 지연의 원인이라고 확정할 수 없습니다.</b> HTTP 시간은 전송+첫 바이트 대기+수신이며, TCP 연결·TLS 수립 시간은 별도 지표입니다.</p>
<h3>5. 자원 부족이 있었는가?</h3><p>표본 최대 FD: JDK SERVERFD개, k6 K6FD개. DB 연결 최대 DBCONN개. Nginx FD·CPU·메모리·DB 풀 대기 시간은 이번에 수집하지 않았습니다. DB 연결 32개는 풀이 열린 개수이지 32개가 계속 바쁘다는 뜻은 아닙니다.</p><p><b>이번 실행에서는 FD 고갈과 연결 오류가 관찰되지 않았습니다.</b> Nginx 유휴 캐시 64개는 활성 연결의 상한이 아니므로, JDK FD가 1천 개를 넘는 것과 모순되지 않습니다.</p></section>
<section id="meaning"><h2>② 원본 리포트 지표 사전</h2><p>항목을 누르면 무엇을 확인할지 펼쳐집니다.</p>
DETAILS
</section><section id="charts"><h2>③ 원본 그래프를 이렇게 보세요</h2><ol><li><b>VUs:</b> 계획한 대로 사용자가 늘고 줄었는지 확인합니다.</li><li><b>Request Rate + p95:</b> 사용자는 늘지만 처리량이 정체되고 p95만 늘면 병목·대기를 의심합니다. 그래프만으로 원인까지 확정하지는 않습니다.</li><li><b>Request Failed:</b> 특히 사용자가 줄어드는 마지막 구간을 보세요. 첫 직접 연결 실험에서는 이때 연결 오류가 관찰됐습니다.</li><li><b>Timings:</b> 연결 수립이 느린지, 응답 첫 바이트 대기가 느린지 구분합니다.</li></ol><p class="note">그래프의 p95는 <b>각 집계 구간의 p95</b>입니다. Summary의 p95는 <b>전체 요청의 p95</b>라 서로 달라도 정상입니다. 구간별 p95를 평균내면 전체 p95가 되지 않습니다. 그래프를 드래그하면 확대, 더블클릭하면 복원됩니다.</p>
<iframe title="k6 원본 시간대별 부하 테스트 그래프" src="k6-report.html"></iframe></section>
<section><h2>이번에 말할 수 있는 결론</h2><p><b>JDK 유휴 연결 기본값 200 + Nginx 유휴 캐시 64개/10초 구성에서, 최대 1,000 VU의 이번 시나리오는 오류 없이 완료됐습니다.</b></p><p>10초 설정 하나의 효과, Nginx의 성능 개선 효과, 운영 최대 처리량은 분리 검증하지 않았습니다. 한 머신에서 k6·서버·DB를 함께 실행했고, TLS·실제 Tomcat·운영 인증 경로도 포함하지 않았습니다. 응답시간 목표(SLO)를 정하지 않아 ‘363ms면 충분히 빠르다’는 판정도 아직 할 수 없습니다.</p><p>다음 성능 판단에는 성공 예약과 매진 응답을 분리한 지연 분포, 더 긴 최대 부하 유지, DB 풀·락 대기와 CPU 측정이 도움이 됩니다.</p><small>출처: 같은 실행의 <a href="result.json">result.json</a>, <a href="k6-summary.json">k6-summary.json</a>, <a href="nginx.conf">Nginx 설정</a>. 지표 정의: <a href="https://grafana.com/docs/k6/latest/using-k6/metrics/reference/">Grafana k6 공식 문서</a>. 이 페이지는 기존 측정 결과의 해설이며 새 부하 테스트를 실행하지 않았습니다.</small></section></main></html>'''
terms=[('Request Rate / http_reqs','초당 HTTP 요청 수. 예약 성공 처리량과 다릅니다. Summary의 rate는 전체 실행 기준 평균입니다.'),('Request Duration / http_req_duration','HTTP 전송·첫 바이트 대기·수신의 합. TCP 연결 수립과 TLS 핸드셰이크는 포함하지 않습니다.'),('avg · med · p90 · p95 · p99 · max','avg는 평균, med는 중앙값. p95는 약 95% 요청이 그 이하인 시간입니다. p99는 더 느린 꼬리 구간이며 max는 단 한 건의 최댓값입니다.'),('Request Failed / http_req_failed','이번 스크립트는 HTTP 200과 409를 정상으로 지정했습니다. 0%라고 전부 예약 성공인 것은 아닙니다. JSON의 passes/fails는 Rate 지표에 true/false가 기록된 횟수여서, http_req_failed의 fails=177053은 요청 실패 177053건을 뜻하지 않습니다. rate=0을 읽으세요.'),('checks','작성한 조건이 참인지 검사한 비율입니다. 이번에는 응답 계약과 최종 상태를 검사했습니다. HTML의 Rates 표에 1/s로 표시되더라도 checks의 값 1은 100% 통과 비율입니다.'),('Request Waiting / http_req_waiting','요청을 보내고 첫 응답 바이트까지 기다리는 시간(TTFB). 서버·프록시·DB 대기가 섞여 있습니다.'),('Request Connecting · TLS handshaking','k6가 Nginx에 연결하는 TCP·TLS 시간입니다. 재사용 연결에서는 0일 수 있습니다. 이번 TLS가 0인 이유는 HTTP 실험이기 때문입니다. Nginx→JDK 연결 시간은 여기 포함되지 않습니다.'),('Request Blocked','요청 시작 전 사용 가능한 TCP 연결 슬롯 등을 기다린 시간. DB 락 대기 지표가 아닙니다.'),('Iteration Duration','가상 사용자의 루프 1회 시간. 예약 성공 시 취소까지 포함하므로 HTTP 요청 1회 시간과 다릅니다.'),('Transfer Rate · data_sent · data_received','네트워크로 보내고 받은 데이터량/초입니다. 요청 수와 함께 보면 요청당 데이터 크기 변화를 이해할 수 있습니다.'),('FD / openFds','프로세스가 연 파일·소켓 등 파일 디스크립터 개수입니다. 연결 수와 완전히 같지 않으며 약 2초 표본은 순간 최대를 놓칠 수 있습니다.')]
html=html.replace('DETAILS',''.join(f'<details><summary>{a}</summary><p>{b}</p></details>' for a,b in terms))
values={'FAILURE':f"{m['http_req_failed']['rate']*100:.1f}%",'P95':f"{d['p(95)']:.2f}",'CREATED':f'{c:,}','SOLD_SHARE':f'{sold/(c+sold)*100:.2f}','SOLD':f'{sold:,}','SHARE':f'{c/(c+sold)*100:.2f}','CHECKS':f"{m['checks']['passes']:,}",'FINALREMAIN':str(r['final']['remaining']),'FINALRES':str(r['final']['reservations']),'ERRORS':str(r['final']['errors']),'VIOLATIONS':str(r['sampledInvariantViolations']),'CANCELLED':f"{r['final']['cancelled']:,}",'REQUESTS':f"{m['http_reqs']['count']:,}",'RPS':f"{m['http_reqs']['rate']:,.0f}",'CREATE_RATE':f"{m['reservations_created']['rate']:.2f}",'AVG':f"{d['avg']:.2f}",'MED':f"{d['med']:.2f}",'MAX':f"{d['max']:.2f}",'SERVERFD':str(r['observedMaxServerFds']),'K6FD':str(r['observedMaxK6Fds']),'DBCONN':str(r['observedMaxMySqlConnections'])}
for k in sorted(values,key=len,reverse=True): html=html.replace(k,values[k])
(p/'k6-guide-ko.html').write_text(html)
print(p/'k6-guide-ko.html')
